# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K8sImageAuditor < Formula
  desc "Audits container images for architecture compatibility"
  homepage "https://github.com/PraveenPrabhuT/k8s-image-auditor"
  version "1.1.5"
  license "MIT"

  depends_on "awscli"
  depends_on "jq"
  depends_on "kubernetes-cli"
  depends_on "pandoc"
  depends_on "skopeo"

  on_macos do
    on_intel do
      url "https://github.com/PraveenPrabhuT/k8s-image-auditor/releases/download/v1.1.5/k8s-image-auditor_1.1.5_darwin_amd64.tar.gz"
      sha256 "99da6069a0c286ad6499bac085e16aab952707b1863ee40125217c58dba1a758"

      def install
        system "make", "install", "PREFIX=#{prefix}"
      end
    end
    on_arm do
      url "https://github.com/PraveenPrabhuT/k8s-image-auditor/releases/download/v1.1.5/k8s-image-auditor_1.1.5_darwin_arm64.tar.gz"
      sha256 "99da6069a0c286ad6499bac085e16aab952707b1863ee40125217c58dba1a758"

      def install
        system "make", "install", "PREFIX=#{prefix}"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/PraveenPrabhuT/k8s-image-auditor/releases/download/v1.1.5/k8s-image-auditor_1.1.5_linux_amd64.tar.gz"
        sha256 "99da6069a0c286ad6499bac085e16aab952707b1863ee40125217c58dba1a758"

        def install
          system "make", "install", "PREFIX=#{prefix}"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/PraveenPrabhuT/k8s-image-auditor/releases/download/v1.1.5/k8s-image-auditor_1.1.5_linux_arm64.tar.gz"
        sha256 "99da6069a0c286ad6499bac085e16aab952707b1863ee40125217c58dba1a758"

        def install
          system "make", "install", "PREFIX=#{prefix}"
        end
      end
    end
  end

  test do
    assert_match "Usage:", shell_output("#{bin}/k8s-image-auditor -h")
  end
end
