# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GrafanaConnect < Formula
  desc "Context-aware Grafana dashboard launcher for Kubernetes"
  homepage "https://github.com/PraveenPrabhuT/grafana-connect"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PraveenPrabhuT/grafana-connect/releases/download/v0.2.0/grafana-connect_0.2.0_darwin_amd64.tar.gz"
      sha256 "2ececdd0d5ec7e8586d1b41022cacadb9f810883e23a0cfb4a88fe7fedf76c05"

      def install
        bin.install "grafana-connect"

        # Install Shell Completions
        bash_completion.install "completions.bash" => "grafana-connect"
        zsh_completion.install "completions.zsh" => "_grafana-connect"
        fish_completion.install "completions.fish" => "grafana-connect.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PraveenPrabhuT/grafana-connect/releases/download/v0.2.0/grafana-connect_0.2.0_darwin_arm64.tar.gz"
      sha256 "94486790e0ab09741194ec063776c1fd861e9da2c4140e3e3ba14c005be00b2a"

      def install
        bin.install "grafana-connect"

        # Install Shell Completions
        bash_completion.install "completions.bash" => "grafana-connect"
        zsh_completion.install "completions.zsh" => "_grafana-connect"
        fish_completion.install "completions.fish" => "grafana-connect.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/PraveenPrabhuT/grafana-connect/releases/download/v0.2.0/grafana-connect_0.2.0_linux_amd64.tar.gz"
      sha256 "bcc2d688737de43e662d2a98c483d7262e3abfc189157acaa730ec26fed721ef"
      def install
        bin.install "grafana-connect"

        # Install Shell Completions
        bash_completion.install "completions.bash" => "grafana-connect"
        zsh_completion.install "completions.zsh" => "_grafana-connect"
        fish_completion.install "completions.fish" => "grafana-connect.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PraveenPrabhuT/grafana-connect/releases/download/v0.2.0/grafana-connect_0.2.0_linux_arm64.tar.gz"
      sha256 "ffb0b9eb0f6982862022625f80034436fd2c6d117a7077f5cea66b3ad8f240d9"
      def install
        bin.install "grafana-connect"

        # Install Shell Completions
        bash_completion.install "completions.bash" => "grafana-connect"
        zsh_completion.install "completions.zsh" => "_grafana-connect"
        fish_completion.install "completions.fish" => "grafana-connect.fish"
      end
    end
  end

  test do
    system "#{bin}/grafana-connect version"
  end
end
