# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GrafanaConnect < Formula
  desc "Context-aware Grafana dashboard launcher for Kubernetes"
  homepage "https://github.com/PraveenPrabhuT/grafana-connect"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PraveenPrabhuT/grafana-connect/releases/download/v0.5.0/grafana-connect_0.5.0_darwin_amd64.tar.gz"
      sha256 "9d28b7d5adcfbb8869eb4247ccf17efe20adce173367b7f7f4687f7f502f1001"

      def install
        bin.install "grafana-connect"

        # Install Shell Completions
        bash_completion.install "completions.bash" => "grafana-connect"
        zsh_completion.install "completions.zsh" => "_grafana-connect"
        fish_completion.install "completions.fish" => "grafana-connect.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PraveenPrabhuT/grafana-connect/releases/download/v0.5.0/grafana-connect_0.5.0_darwin_arm64.tar.gz"
      sha256 "62fdae86306b5e16b7f82c1b6df720f7e6f6311ae423ace5a9bb41e812d62302"

      def install
        bin.install "grafana-connect"

        # Install Shell Completions
        bash_completion.install "completions.bash" => "grafana-connect"
        zsh_completion.install "completions.zsh" => "_grafana-connect"
        fish_completion.install "completions.fish" => "grafana-connect.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/PraveenPrabhuT/grafana-connect/releases/download/v0.5.0/grafana-connect_0.5.0_linux_amd64.tar.gz"
      sha256 "36b190dd52cde355d5fa92c1894c15fae22e96eb53e54bbac5942199706a6d07"
      def install
        bin.install "grafana-connect"

        # Install Shell Completions
        bash_completion.install "completions.bash" => "grafana-connect"
        zsh_completion.install "completions.zsh" => "_grafana-connect"
        fish_completion.install "completions.fish" => "grafana-connect.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PraveenPrabhuT/grafana-connect/releases/download/v0.5.0/grafana-connect_0.5.0_linux_arm64.tar.gz"
      sha256 "0d54f90aadc4465f2350531c5907000cfb0f74ccb41da010426a59511cc41fdd"
      def install
        bin.install "grafana-connect"

        # Install Shell Completions
        bash_completion.install "completions.bash" => "grafana-connect"
        zsh_completion.install "completions.zsh" => "_grafana-connect"
        fish_completion.install "completions.fish" => "grafana-connect.fish"
      end
    end
  end

  test do
    system "#{bin}/grafana-connect version"
  end
end
