# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GrafanaConnect < Formula
  desc "Context-aware Grafana dashboard launcher for Kubernetes"
  homepage "https://github.com/PraveenPrabhuT/grafana-connect"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PraveenPrabhuT/grafana-connect/releases/download/v0.1.0/grafana-connect_0.1.0_darwin_amd64.tar.gz"
      sha256 "54906315eac05e5c34e75b92a422757700b5895518e878477587549ad0d84fbc"

      def install
        bin.install "grafana-connect"

        # Install Shell Completions
        bash_completion.install "completions.bash" => "grafana-connect"
        zsh_completion.install "completions.zsh" => "_grafana-connect"
        fish_completion.install "completions.fish" => "grafana-connect.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PraveenPrabhuT/grafana-connect/releases/download/v0.1.0/grafana-connect_0.1.0_darwin_arm64.tar.gz"
      sha256 "36ba97d4b7c906c962b589311806f301848e86831a3fe8e3bca90b2aae7e7dc3"

      def install
        bin.install "grafana-connect"

        # Install Shell Completions
        bash_completion.install "completions.bash" => "grafana-connect"
        zsh_completion.install "completions.zsh" => "_grafana-connect"
        fish_completion.install "completions.fish" => "grafana-connect.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/PraveenPrabhuT/grafana-connect/releases/download/v0.1.0/grafana-connect_0.1.0_linux_amd64.tar.gz"
      sha256 "10d691df5858112267cfcba7e594da442cd2672f85d8e910ffa242131543e629"
      def install
        bin.install "grafana-connect"

        # Install Shell Completions
        bash_completion.install "completions.bash" => "grafana-connect"
        zsh_completion.install "completions.zsh" => "_grafana-connect"
        fish_completion.install "completions.fish" => "grafana-connect.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PraveenPrabhuT/grafana-connect/releases/download/v0.1.0/grafana-connect_0.1.0_linux_arm64.tar.gz"
      sha256 "5cdca79bcca035513d0d0d5c0b0dd5617311b25f6e539a0e5b1608e4d0925734"
      def install
        bin.install "grafana-connect"

        # Install Shell Completions
        bash_completion.install "completions.bash" => "grafana-connect"
        zsh_completion.install "completions.zsh" => "_grafana-connect"
        fish_completion.install "completions.fish" => "grafana-connect.fish"
      end
    end
  end

  test do
    system "#{bin}/grafana-connect version"
  end
end
