# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K8sImageAuditor < Formula
  desc "Audits container images for architecture compatibility"
  homepage "https://github.com/PraveenPrabhuT/k8s-image-auditor"
  version "1.1.7"
  license "MIT"

  depends_on "awscli"
  depends_on "jq"
  depends_on "kubernetes-cli"
  depends_on "pandoc"
  depends_on "skopeo"

  on_macos do
    on_intel do
      url "https://github.com/PraveenPrabhuT/k8s-image-auditor/releases/download/v1.1.7/k8s-image-auditor_1.1.7_darwin_amd64.tar.gz"
      sha256 "c513ac089ae07c64a6a27bc23996b8f3f78c3500a2983670b4c4fd0dce0c8cc5"

      def install
        system "make", "install", "PREFIX=#{prefix}"
      end
    end
    on_arm do
      url "https://github.com/PraveenPrabhuT/k8s-image-auditor/releases/download/v1.1.7/k8s-image-auditor_1.1.7_darwin_arm64.tar.gz"
      sha256 "c513ac089ae07c64a6a27bc23996b8f3f78c3500a2983670b4c4fd0dce0c8cc5"

      def install
        system "make", "install", "PREFIX=#{prefix}"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/PraveenPrabhuT/k8s-image-auditor/releases/download/v1.1.7/k8s-image-auditor_1.1.7_linux_amd64.tar.gz"
        sha256 "c513ac089ae07c64a6a27bc23996b8f3f78c3500a2983670b4c4fd0dce0c8cc5"

        def install
          system "make", "install", "PREFIX=#{prefix}"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/PraveenPrabhuT/k8s-image-auditor/releases/download/v1.1.7/k8s-image-auditor_1.1.7_linux_arm64.tar.gz"
        sha256 "c513ac089ae07c64a6a27bc23996b8f3f78c3500a2983670b4c4fd0dce0c8cc5"

        def install
          system "make", "install", "PREFIX=#{prefix}"
        end
      end
    end
  end

  test do
    assert_match "Usage:", shell_output("#{bin}/k8s-image-auditor -h")
  end
end
