# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K8sImageAuditor < Formula
  desc "Audits container images for architecture compatibility"
  homepage "https://github.com/PraveenPrabhuT/k8s-image-auditor"
  version "1.1.9"
  license "MIT"

  depends_on "awscli"
  depends_on "jq"
  depends_on "kubernetes-cli"
  depends_on "pandoc"
  depends_on "skopeo"

  on_macos do
    on_intel do
      url "https://github.com/PraveenPrabhuT/k8s-image-auditor/releases/download/v1.1.9/k8s-image-auditor_1.1.9_darwin_amd64.tar.gz"
      sha256 "06084e8c5d4663314f26f7d297292092b7e5470a7e6b14c6391aae68d087cb0f"

      def install
        system "make", "install", "PREFIX=#{prefix}"
      end
    end
    on_arm do
      url "https://github.com/PraveenPrabhuT/k8s-image-auditor/releases/download/v1.1.9/k8s-image-auditor_1.1.9_darwin_arm64.tar.gz"
      sha256 "06084e8c5d4663314f26f7d297292092b7e5470a7e6b14c6391aae68d087cb0f"

      def install
        system "make", "install", "PREFIX=#{prefix}"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/PraveenPrabhuT/k8s-image-auditor/releases/download/v1.1.9/k8s-image-auditor_1.1.9_linux_amd64.tar.gz"
        sha256 "06084e8c5d4663314f26f7d297292092b7e5470a7e6b14c6391aae68d087cb0f"

        def install
          system "make", "install", "PREFIX=#{prefix}"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/PraveenPrabhuT/k8s-image-auditor/releases/download/v1.1.9/k8s-image-auditor_1.1.9_linux_arm64.tar.gz"
        sha256 "06084e8c5d4663314f26f7d297292092b7e5470a7e6b14c6391aae68d087cb0f"

        def install
          system "make", "install", "PREFIX=#{prefix}"
        end
      end
    end
  end

  test do
    assert_match "Usage:", shell_output("#{bin}/k8s-image-auditor -h")
  end
end
