# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rds < Formula
  desc "Context-aware AWS RDS toolkit with native Go fallback"
  homepage "https://github.com/PraveenPrabhuT/rds"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PraveenPrabhuT/rds/releases/download/v0.3.1/rds_0.3.1_darwin_amd64.tar.gz"
      sha256 "01dbd79c5027a4230df19a34a442d1d0de7c736d98651c3d6c43d43b8ac28d89"

      def install
        bin.install "rds"

        # Install Shell Completions
        bash_completion.install "completions.bash" => "rds"
        zsh_completion.install "completions.zsh" => "_rds"
        fish_completion.install "completions.fish" => "rds.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PraveenPrabhuT/rds/releases/download/v0.3.1/rds_0.3.1_darwin_arm64.tar.gz"
      sha256 "41147de767f7dbca3d2826005f4e134042c2b25d145081a7b4d440304cade62b"

      def install
        bin.install "rds"

        # Install Shell Completions
        bash_completion.install "completions.bash" => "rds"
        zsh_completion.install "completions.zsh" => "_rds"
        fish_completion.install "completions.fish" => "rds.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/PraveenPrabhuT/rds/releases/download/v0.3.1/rds_0.3.1_linux_amd64.tar.gz"
      sha256 "d40c8052f0f3d185acbd35340c9aa952ef048b8ddd498ea75129b4aaaac5ad42"
      def install
        bin.install "rds"

        # Install Shell Completions
        bash_completion.install "completions.bash" => "rds"
        zsh_completion.install "completions.zsh" => "_rds"
        fish_completion.install "completions.fish" => "rds.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PraveenPrabhuT/rds/releases/download/v0.3.1/rds_0.3.1_linux_arm64.tar.gz"
      sha256 "ab354022fd034b82d4fbb73b9bb9b220635edad3694636d1679dca2ddfc1693b"
      def install
        bin.install "rds"

        # Install Shell Completions
        bash_completion.install "completions.bash" => "rds"
        zsh_completion.install "completions.zsh" => "_rds"
        fish_completion.install "completions.fish" => "rds.fish"
      end
    end
  end

  test do
    system "#{bin}/rds --version"
  end
end
