# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rds < Formula
  desc "Context-aware AWS RDS toolkit with native Go fallback"
  homepage "https://github.com/PraveenPrabhuT/rds"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PraveenPrabhuT/rds/releases/download/v0.4.1/rds_0.4.1_darwin_amd64.tar.gz"
      sha256 "e1543099c102d446419f176835eaec1bb81131fb1da17aef158994e71dc77ead"

      def install
        bin.install "rds"

        # Install Shell Completions
        bash_completion.install "completions.bash" => "rds"
        zsh_completion.install "completions.zsh" => "_rds"
        fish_completion.install "completions.fish" => "rds.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PraveenPrabhuT/rds/releases/download/v0.4.1/rds_0.4.1_darwin_arm64.tar.gz"
      sha256 "82bc43df64f6245aad898338abee1368736d3a3d3392ff05fe229e02b0529c48"

      def install
        bin.install "rds"

        # Install Shell Completions
        bash_completion.install "completions.bash" => "rds"
        zsh_completion.install "completions.zsh" => "_rds"
        fish_completion.install "completions.fish" => "rds.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/PraveenPrabhuT/rds/releases/download/v0.4.1/rds_0.4.1_linux_amd64.tar.gz"
      sha256 "7d15114b4d88f810213314e98d1bf05de4fb1306f0c9ac2e523a6f1e1b1cb8d7"
      def install
        bin.install "rds"

        # Install Shell Completions
        bash_completion.install "completions.bash" => "rds"
        zsh_completion.install "completions.zsh" => "_rds"
        fish_completion.install "completions.fish" => "rds.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PraveenPrabhuT/rds/releases/download/v0.4.1/rds_0.4.1_linux_arm64.tar.gz"
      sha256 "2f0c14a01f1abfd38b51d81ca04d5cefe79c36c2282591d3be55b0333a6eba71"
      def install
        bin.install "rds"

        # Install Shell Completions
        bash_completion.install "completions.bash" => "rds"
        zsh_completion.install "completions.zsh" => "_rds"
        fish_completion.install "completions.fish" => "rds.fish"
      end
    end
  end

  test do
    system "#{bin}/rds --version"
  end
end
