# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rds < Formula
  desc "Context-aware AWS RDS toolkit with native Go fallback"
  homepage "https://github.com/PraveenPrabhuT/rds"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PraveenPrabhuT/rds/releases/download/v0.1.0/rds_0.1.0_darwin_amd64.tar.gz"
      sha256 "dd8f1a0de0eaee07ee36bf937d0049c0b20145e91aee7fe4acf8cc5356b17b53"

      def install
        bin.install "rds"

        # Install Shell Completions
        bash_completion.install "completions.bash" => "rds"
        zsh_completion.install "completions.zsh" => "_rds"
        fish_completion.install "completions.fish" => "rds.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PraveenPrabhuT/rds/releases/download/v0.1.0/rds_0.1.0_darwin_arm64.tar.gz"
      sha256 "8b7de6deac66b3ed16b3e073aebef8c0dcbb0a81e084a0a7ed5f0b96daeb3ac8"

      def install
        bin.install "rds"

        # Install Shell Completions
        bash_completion.install "completions.bash" => "rds"
        zsh_completion.install "completions.zsh" => "_rds"
        fish_completion.install "completions.fish" => "rds.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/PraveenPrabhuT/rds/releases/download/v0.1.0/rds_0.1.0_linux_amd64.tar.gz"
      sha256 "bad924c65f9e3885c242a862d664c5d76af811e6f96055920e4b757bb0d9a565"
      def install
        bin.install "rds"

        # Install Shell Completions
        bash_completion.install "completions.bash" => "rds"
        zsh_completion.install "completions.zsh" => "_rds"
        fish_completion.install "completions.fish" => "rds.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PraveenPrabhuT/rds/releases/download/v0.1.0/rds_0.1.0_linux_arm64.tar.gz"
      sha256 "bf83783b6b72d98c27593b2c2a102f501e09b4f64743418317c247b21e09fd9c"
      def install
        bin.install "rds"

        # Install Shell Completions
        bash_completion.install "completions.bash" => "rds"
        zsh_completion.install "completions.zsh" => "_rds"
        fish_completion.install "completions.fish" => "rds.fish"
      end
    end
  end

  test do
    system "#{bin}/rds --version"
  end
end
