# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vpn < Formula
  desc "The Byte-Smith's VPN Orchestrator"
  homepage "https://github.com/PraveenPrabhuT/qvpn"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/PraveenPrabhuT/qvpn/releases/download/v1.0.0/vpn_1.0.0_darwin_amd64.tar.gz"
      sha256 "0aaf12ca1183fd82fe92955c631a5c48d76db290f02c3e52515d71338617fbfd"

      def install
        bin.install "vpn"

        # Bash completions
        bash_completion.install "completions.bash" => "vpn"
        # Zsh completions (Must be renamed to _vpn)
        zsh_completion.install "completions.zsh" => "_vpn"
        # Fish completions
        fish_completion.install "completions.fish" => "vpn.fish"
      end
    end
    on_arm do
      url "https://github.com/PraveenPrabhuT/qvpn/releases/download/v1.0.0/vpn_1.0.0_darwin_arm64.tar.gz"
      sha256 "e06b92b0d29a0a76936bb6d885526553c19b1be379f05b90465f1b00a2d16914"

      def install
        bin.install "vpn"

        # Bash completions
        bash_completion.install "completions.bash" => "vpn"
        # Zsh completions (Must be renamed to _vpn)
        zsh_completion.install "completions.zsh" => "_vpn"
        # Fish completions
        fish_completion.install "completions.fish" => "vpn.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/PraveenPrabhuT/qvpn/releases/download/v1.0.0/vpn_1.0.0_linux_amd64.tar.gz"
        sha256 "7f31a2ac36a779d01b5d338c2cc0059a0550b4a125e05af3dc1d6fc832f6c74a"

        def install
          bin.install "vpn"

          # Bash completions
          bash_completion.install "completions.bash" => "vpn"
          # Zsh completions (Must be renamed to _vpn)
          zsh_completion.install "completions.zsh" => "_vpn"
          # Fish completions
          fish_completion.install "completions.fish" => "vpn.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/PraveenPrabhuT/qvpn/releases/download/v1.0.0/vpn_1.0.0_linux_arm64.tar.gz"
        sha256 "be51c2ec9906ced0c501c310d2f6352ed18791e70e65de4565dd99486ddd157c"

        def install
          bin.install "vpn"

          # Bash completions
          bash_completion.install "completions.bash" => "vpn"
          # Zsh completions (Must be renamed to _vpn)
          zsh_completion.install "completions.zsh" => "_vpn"
          # Fish completions
          fish_completion.install "completions.fish" => "vpn.fish"
        end
      end
    end
  end

  test do
    system "#{bin}/vpn --help"
  end
end
