# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vpn < Formula
  desc "The Byte-Smith's VPN Orchestrator"
  homepage "https://github.com/PraveenPrabhuT/qvpn"
  version "0.1.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/PraveenPrabhuT/qvpn/releases/download/v0.1.3/vpn_0.1.3_darwin_amd64.tar.gz"
      sha256 "0f67d008019597bbb08763e22d3eef5ba7c8e6473a8e96dc5290f2e6b52233da"

      def install
        bin.install "vpn"

        # Install completions if you generated them
        # (We can add generation steps later, for now just binary)
        # bash_completion.install "completions.bash" => "vpn"
        # zsh_completion.install "completions.zsh" => "_vpn"
      end
    end
    on_arm do
      url "https://github.com/PraveenPrabhuT/qvpn/releases/download/v0.1.3/vpn_0.1.3_darwin_arm64.tar.gz"
      sha256 "b164af5e9ef3c62ae6b00877a45fc3a4bf16376d238ab296f9e0341e9c343243"

      def install
        bin.install "vpn"

        # Install completions if you generated them
        # (We can add generation steps later, for now just binary)
        # bash_completion.install "completions.bash" => "vpn"
        # zsh_completion.install "completions.zsh" => "_vpn"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/PraveenPrabhuT/qvpn/releases/download/v0.1.3/vpn_0.1.3_linux_amd64.tar.gz"
        sha256 "cc23be2db8ec13c1fb93419b1b8cd1de34f7a0218cdc92a50119005567b7933f"

        def install
          bin.install "vpn"

          # Install completions if you generated them
          # (We can add generation steps later, for now just binary)
          # bash_completion.install "completions.bash" => "vpn"
          # zsh_completion.install "completions.zsh" => "_vpn"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/PraveenPrabhuT/qvpn/releases/download/v0.1.3/vpn_0.1.3_linux_arm64.tar.gz"
        sha256 "5b2580e2c23eddc96ef51d99638368b0986083ce170b044794f83f420d833c7a"

        def install
          bin.install "vpn"

          # Install completions if you generated them
          # (We can add generation steps later, for now just binary)
          # bash_completion.install "completions.bash" => "vpn"
          # zsh_completion.install "completions.zsh" => "_vpn"
        end
      end
    end
  end

  test do
    system "#{bin}/vpn --help"
  end
end
